name: Yelb CI/CD Pipeline

on:
  push:
    branches: [ "feature" ]

jobs:
  build-test-push:
    runs-on: self-hosted  # Make sure your runner has Docker + Trivy installed

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    #   JFROG_URL: ${{ secrets.JFROG_URL }}
    #   JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      ## Build All Images

      - name: Build yelb-db
        run: docker build -t yelb-db yelb-db

      - name: Build yelb-appserver
        run: docker build -t yelb-appserver yelb-appserver

      - name: Build yelb-ui
        run: docker build -t yelb-ui yelb-ui

      ## Scan with Trivy     

      - name: Scan images with Trivy
        run: |
          trivy image yelb-ui > yelb-ui-scan.txt
          trivy image yelb-appserver > yelb-appserver-scan.txt

      ## Dockerfile Linting
      # - name: Lint Dockerfiles
      #   run: |
      #     docker run --rm -i hadolint/hadolint < ./yelb-ui/Dockerfile
      #     docker run --rm -i hadolint/hadolint < ./yelb-appserver/Dockerfile
      - name: Lint Dockerfiles (Ignore errors)
        run: |
         docker run --rm -i hadolint/hadolint < ./yelb-ui/Dockerfile || true
         docker run --rm -i hadolint/hadolint < ./yelb-appserver/Dockerfile || true
         docker run --rm -i hadolint/hadolint < ./yelb-db/Dockerfile || true
         
      ## Push to DockerHub
      - name: Login to DockerHub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Tag and Push Images
        run: |
          docker tag yelb-ui ${DOCKERHUB_USERNAME}/yelb-ui:latest
          docker tag yelb-appserver ${DOCKERHUB_USERNAME}/yelb-appserver:latest
          docker tag yelb-db ${DOCKERHUB_USERNAME}/yelb-db:latest
          docker tag redis:4.0.2 ${DOCKERHUB_USERNAME}/yelb-redis:latest

          docker push ${DOCKERHUB_USERNAME}/yelb-ui:latest
          docker push ${DOCKERHUB_USERNAME}/yelb-appserver:latest
          docker push ${DOCKERHUB_USERNAME}/yelb-db:latest
          docker push ${DOCKERHUB_USERNAME}/yelb-redis:latest

      # #############################
      # ## Upload to JFrog Artifactory
      # #############################

      # - name: Upload scan logs to JFrog
      #   run: |
      #     curl -H "X-JFrog-Art-Api:${JFROG_API_KEY}" -T yelb-ui-scan.txt "${JFROG_URL}/yelb/yelb-ui-scan.txt"
      #     curl -H "X-JFrog-Art-Api:${JFROG_API_KEY}" -T yelb-appserver-scan.txt "${JFROG_URL}/yelb/yelb-appserver-scan.txt"

      #############################
      ## Staging Deployment
      #############################
      - name: Login to DockerHub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Run containers for staging
        run: |
          docker network create yelb-network
          docker run -d --network yelb-network --name  yelb-db ${DOCKERHUB_USERNAME}/yelb-db
          docker run -d --network yelb-network --name  yelb-redis -p 6379:6379 ${DOCKERHUB_USERNAME}/yelb-redis
          docker run -d --network yelb-network --name yelb-appserver -p 4567:4567 ${DOCKERHUB_USERNAME}/yelb-appserver
          docker run -d --network yelb-network --name yelb-ui -p 80:80 ${DOCKERHUB_USERNAME}/yelb-ui

      # #############################
      # ## Email Notification
      # #############################

      # - name: Send success email
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 587
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: Yelb CI/CD Pipeline - Success 🎉
      #     to: your-team@example.com
      #     from: yelb-pipeline@example.com
      #     body: |
      #       ✅ The Yelb CI/CD pipeline completed successfully!
      #       - Images built and scanned
      #       - DockerHub and JFrog uploads completed
      #       - Staging deployment running

